# ---- Build stage ----
FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/filmsync-operator ./cmd/filmsync-operator

# ---- Final stage ----
FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /app

COPY --from=builder /out/filmsync-operator .

USER nonroot:nonroot

EXPOSE 8081

ENTRYPOINT ["/app/filmsync-operator"]
